package com.collabsync.backend.kafka.enums;

public enum EventType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COLLAB_USER_CHANGED,
    TASK_ASSIGNED,
    USER_MENTIONED,
}
